### PR TITLE
ci: use local version for PRs

### PR DESCRIPTION
**Pull request by Borda**
this enables proper testing of a change from PR :flamingo: 
atm any PR is not really testing code that is changed but the code from the master...

cc: @jamesmortensen

### CODE REVIEW

**Comment by jamesmortensen** [comment]
Hi @Borda thanks again for the contributions.  

Initially, this CI workflow was setup as a demo, I think because I didn't yet have a plan for how to validate automatically that the action behaves correctly for both cache hits and cache misses.  Since there's no assertions, you can see that both jobs are passing, even though it's not actually validating whether or not a cache miss or cache hit happened.  

In fact, you can see that both "cache miss" and "cache hit" jobs are executing the "Run this if there is a cache hit" step.  The only way to validate the action is working is by reading the steps manually.  

Screenshot 2023-12-15 at 5 10 41 AM

I'm not sure the changes is sufficient to validate that the action is functioning correctly.  What do you think?

**Comment by Borda** [comment]
> I'm not sure the changes is sufficient to validate that the action is functioning correctly. What do you think?

if I got what you mean we can simply add some crash meaning:
```yaml
- name: this shall not ever happen
  if: output.my-name != ''
  run: exit 1
```
which will make the workflow fail and so PR shall not be merged

**Comment by Borda** [comment]
so updating this PR such as:
```yaml
      - name: Show output of cache hit
        run: echo "${{ steps.cache-container-images.outputs.cache-hit }}"

      - name: Terminate if cache was not hit
        if: ${{ steps.cache-container-images.outputs.cache-hit != 'true' }}
        run: exit 1
```

**Comment by Borda** [comment]
@jamesmortensen mind checking the updated version :chipmunk:

**Comment by Borda** [comment]
@jamesmortensen how is it going? :flamingo:

**Comment by jamesmortensen** [comment]
Hi @Borda sorry for the delay and lack of communication in getting to this.  (Going through a transition from one country to another and still getting settled in).

I went ahead and merged.  Thanks again!

**Pull request merged**
